### ISSUE TITLE
Cannot open resource with notebook editor type 'pwshnb'

### ISSUE THREAD

**Issue by InTEGr8or** [TylerLeonhardt/shell-runner-notebooks#9]
I get this error when trying to open a new, empty file `test.Notebook.ps1`

`Cannot open resource with notebook editor type 'pwshnb', please check if you have the right extension installed or enabled.`

It also happens for existing `.ps1` that I convert to Notebooks.

**Comment by TylerLeonhardt** [comment]
Should be fixed now.
